### ISSUE TITLE
Add option to hide window without system tray icon

### ISSUE THREAD

**Issue by SleepDaemon** [PhantomGamers/SFP#1]
I want to Hide the program from both tray and taskbar so I have these settings. But with these settings when I minimize it keeps the taskbar icon which I don't want, and when I close the window it closes the whole program. But I wish to have it running in the background in case steam decides to update it self. I was able to achieve this on Steam Friend Patcher.

![2022-05-15_07-34](https://user-images.githubusercontent.com/88533953/168457467-62893305-ac1a-40d0-9d29-0bdc1549f591.png)

Image of Taskbar
![2022-05-15_07-36](https://user-images.githubusercontent.com/88533953/168457497-fec095ff-81f5-4895-9d53-959b4e505cc7.png)

**Comment by SleepDaemon** [comment]
I found another problem, every time I click the .exe, it runs a whole new instance instead of opening the existing one.

**Comment by PhantomGamers** [comment]
> I found another problem, every time I click the .exe, it runs a whole new instance instead of opening the existing one.

So this is actually why the behavior that was included in the old patcher is not included in this one. You have to be able to access a running instance of SFP no matter what and as I currently don't have a way to open the existing one you have to choose between having a taskbar icon or having a tray icon.

The reason I can't just copy the behavior directly from the old patcher is that this patcher is intended to be cross platform compatible and as far as I know there is no built in way to both enforce a single instance of an application and communicate with an already running instance which works across platforms.

I do plan to look into this further, and if anything I might just include the functionality only for the Windows version, but I can't give any kind of ETA on when this will be accomplished.

This is one of the reasons I hesitated to push the update to the old patcher informing people to switch to this one as it does not have complete feature parity yet, but I decided to do so anyway because there was an influx of help requests caused by Valve's recent update to the library.

**Comment by SleepDaemon** [comment]
aight thanks

**Comment by SleepDaemon** [comment]
Ran into another problem where SFP gives a crash popup when I restart my laptop.

**Comment by PhantomGamers** [comment]
If you have issues other than the one described in this post, please post it in its own issue.

Also please make sure your issue is not a known issue.

https://github.com/PhantomGamers/SFP#known-issues

**Comment by PhantomGamers** [comment]
This is finally implemented in the latest prerelease for the Steam beta! :D https://github.com/PhantomGamers/SFP/releases/tag/0.0.31-alpha
