### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by syneekis415** [PhantomGamers/SFP#28]
As a windows 7 user its very sad that this program does not support windows 7.
Windows 7 is maybe old but is getting still official ESU updates, also last year 5% of all steam users where using Windows 7*
so its still very popular os and for a reason cause its "last good windows version"

Please consider adding windows 7 support as there is really no any reason to not add that and Steam does also support windows 7

*(source https://www.statista.com/statistics/265033/proportion-of-operating-systems-used-on-the-online-gaming-platform-steam/)
(Error i got: System.NotSupportedException: Windows versions earlier than 10 are not supported)

**Comment by PhantomGamers** [comment]
This won't happen since the UI theme used by SFP does not support Windows 7 https://github.com/amwx/FluentAvalonia

Moreover, I don't think corporate users are going to be interested in using SFP and personal users absolutely should just move onto a modern OS. I have zero interest in supporting stubborn people.

**Comment by kr0tchet** [comment]
> As a windows 7 user its very sad that this program does not support windows 7. Windows 7 is maybe old but is getting still official ESU updates, also last year 5% of all steam users where using Windows 7* so its still very popular os and for a reason cause its "last good windows version"
> 
> Please consider adding windows 7 support as there is really no any reason to not add that and Steam does also support windows 7
> 
> *(source https://www.statista.com/statistics/265033/proportion-of-operating-systems-used-on-the-online-gaming-platform-steam/) (Error i got: System.NotSupportedException: Windows versions earlier than 10 are not supported)

The software now works with Windows 7 this time, without any errors with latest version, but the only issues is basically that if you are trying to go to settings, it would crash SFP as the UI itself would require Win10/11 to work, again this will never be fixed since almost nobody uses Win7 except for compatibility with older applications, drivers, PC or simply for retro gaming.
